apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-node-app-deployment
  labels:
    app: k8s-node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-node-app
  template:
    metadata:
      labels:
        app: k8s-node-app 
    spec:
      containers:
      - name: node-server
        image: cuu2252/k8s-node-app:latest
        ports:
        - containerPort: 3000
        
        
---

apiVersion: v1
kind: Service
metadata:
  name: k8s-node-app-service
spec:
  selector:
    app: k8s-node-app 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
    nodePort: 31234
